name: Fortify SAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fortify-sast-scan:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Configuração do ambiente Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Passo 3: Configuração de variáveis de ambiente e execução do scan
      - name: Run Fortify SAST Scan
        uses: fortify/github-action@a92347297e02391b857e7015792cd1926a4cd418
        with:
          sast-scan: true
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: dev-gubqx51ndecuf3as
          FOD_USER: preferencial
          # Use o segredo do GitHub para a senha
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}

      # Passo 4: Configuração do valor padrão de FOD_RELEASE
      - name: Set FOD_RELEASE default value
        run: |
          export FOD_RELEASE="${APP}:${REL}"
          echo FOD_RELEASE=$FOD_RELEASE >> $GITHUB_ENV
        env:
          APP: zk4stv/election
          REL: main

      # Passo 5: Instalação de ferramentas Fortify
      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v1.2.2
        with:
          export-path: false
          fcli: action-default
          sc-client: skip
          fod-uploader: skip
          vuln-exporter: skip
          bugtracker-utility: skip
          debricked-cli: skip
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          FOD_RELEASE: zk4stv/election:main
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: dev-gubqx51ndecuf3as
          FOD_USER: preferencial
          # Use o segredo do GitHub para a senha
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}

      # Passo 6: Validação de variáveis de ambiente antes do login
      - name: Validate Fortify FoD Login
        run: |
          if [ -z "$FOD_URL" ]; then
            echo "ERROR: FOD_URL environment variable must be set"; exit 1;
          fi
          if [ -z "$FOD_TENANT" ]; then
            echo "ERROR: FOD_TENANT environment variable must be set"; exit 1;
          fi
          if [ -z "$FOD_USER" ]; then
            echo "ERROR: FOD_USER environment variable must be set"; exit 1;
          fi
          if [ -z "$FOD_PASSWORD" ]; then
            echo "ERROR: FOD_PASSWORD environment variable must be set"; exit 1;
          fi
          echo "All environment variables are set correctly."
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: dev-gubqx51ndecuf3as
          FOD_USER: preferencial
          # Use o segredo do GitHub para a senha
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}

      # Passo 7: Tentativa de login no Fortify
      - name: Fortify FoD Login
        run: |
          echo "Attempting to log in..."
          /home/runner/work/_temp/fortify/tools/fcli/aHR0cHM6Ly9naXRodWIuY29tL2ZvcnRpZnkvZmNsaS9yZWxlYXNlcy9kb3dubG9hZC92Mi4zLjAvZmNsaS1saW51eC50Z3o=/bin/fcli fod session login \
            --url https://ams.fortify.com \
            -t "${{ env.FOD_TENANT }}" \
            -u "${{ env.FOD_USER }}" \
            -p "${{ secrets.FOD_PASSWORD }}"
        env:
          FCLI_INSTALL_DIR: /home/runner/work/_temp/fortify/tools/fcli/aHR0cHM6Ly9naXRodWIuY29tL2ZvcnRpZnkvZmNsaS9yZWxlYXNlcy9kb3dubG9hZC92Mi4zLjAvZmNsaS1saW51eC50Z3o=
          FCLI_BIN_DIR: /home/runner/work/_temp/fortify/tools/fcli/aHR0cHM6Ly9naXRodWIuY29tL2ZvcnRpZnkvZmNsaS9yZWxlYXNlcy9kb3dubG9hZC92Mi4zLjAvZmNsaS1saW51eC50Z3o=/bin
          FCLI_CMD: /home/runner/work/_temp/fortify/tools/fcli/aHR0cHM6Ly9naXRodWIuY29tL2ZvcnRpZnkvZmNsaS9yZWxlYXNlcy9kb3dubG9hZC92Mi4zLjAvZmNsaS1saW51eC50Z3o=/bin/fcli
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: dev-gubqx51ndecuf3as
          FOD_USER: preferencial
          # Use o segredo do GitHub para a senha
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}

      # Passo 8: Execução da ação Fortify (após login bem-sucedido)
      - name: Run Fortify FoD SAST Scan
        run: |
          echo "Running FoD SAST Scan..."
          "${FCLI_CMD}" fod release start-scan \
            --release-id "${FOD_RELEASE}" \
            --scan-type "Dynamic" \
            --assessment-type "Standard"
        env:
          FOD_URL: https://ams.fortify.com
          FCLI_CMD: /home/runner/work/_temp/fortify/tools/fcli/aHR0cHM6Ly9naXRodWIuY29tL2ZvcnRpZnkvZmNsaS9yZWxlYXNlcy9kb3dubG9hZC92Mi4zLjAvZmNsaS1saW51eC50Z3o=/bin/fcli
          FOD_RELEASE: zk4stv/election:main
          # Use o segredo do GitHub para a senha
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}
