name: Fortify SAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fortify-sast:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Fortify SAST Scan
        uses: fortify/github-action@a92347297e02391b857e7015792cd1926a4cd418
        with:
          sast-scan: true
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: dev-gubqx51ndecuf3as
          FOD_USER: preferencial
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}

      - name: Run Fortify FoD SAST Scan
        uses: fortify/github-action/fod-sast-scan@v1.2.2
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: dev-gubqx51ndecuf3as
          FOD_USER: preferencial
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}

      - name: Set FOD_RELEASE default value
        run: |
          export FOD_RELEASE="${APP}:${REL}"
          echo FOD_RELEASE=$FOD_RELEASE >> $GITHUB_ENV
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: dev-gubqx51ndecuf3as
          FOD_USER: preferencial
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}
          APP: zk4stv/election
          REL: main

      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v1.2.2
        with:
          export-path: false
          fcli: action-default
          sc-client: skip
          fod-uploader: skip
          vuln-exporter: skip
          bugtracker-utility: skip
          debricked-cli: skip
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          FOD_RELEASE: zk4stv/election:main
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: dev-gubqx51ndecuf3as
          FOD_USER: preferencial
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}

      - name: Fortify FoD Login
        run: |
          if [ -z "$FOD_URL" ]; then
            echo "ERROR: Either FOD_CLIENT_ID and FOD_CLIENT_SECRET, or FOD_TENANT, FOD_USER and FOD_PASSWORD environment variables must be set"
            exit 1
          fi
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: dev-gubqx51ndecuf3as
          FOD_USER: preferencial
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}