name: Fortify SCA Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fortify-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Fortify CLI
        run: |
          # Tentar encontrar o binário da Fortify CLI localmente
          if ! command -v fcli &> /dev/null; then
            echo "Fortify CLI não encontrada, instalando manualmente."
            # Download do Fortify CLI de uma URL válida
            curl -f -sSL https://download-url/fortify-cli.sh -o install_fortify.sh || { echo "Erro ao baixar Fortify CLI"; exit 1; }
            
            # Exibir o script baixado para garantir que não há erros
            cat install_fortify.sh
            
            # Tornar o script executável e executar a instalação
            chmod +x install_fortify.sh
            ./install_fortify.sh
          else
            echo "Fortify CLI já está instalada."
          fi

      - name: Verify Fortify CLI Installation
        run: |
          # Verificar se a Fortify CLI foi instalada corretamente
          if command -v fcli &> /dev/null; then
            fcli --version
          else
            echo "Erro: Fortify CLI não foi instalada corretamente."
            exit 1
          fi

      - name: Run Fortify Scan
        run: |
          # Executar a análise Fortify no código do repositório
          fcli translate -o build_id
          fcli scan -b build_id -o results.fpr

        env:
          FOD_URL: ${{ secrets.FOD_URL }}
          FOD_USERNAME: ${{ secrets.FOD_USERNAME }}
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}
          FOD_RELEASE: ${{ secrets.FOD_RELEASE }}

      - name: Upload results to Fortify on Demand
        run: |
          # Submeter os resultados da análise para o Fortify on Demand
          fcli upload -release ${{ env.FOD_RELEASE }} -f results.fpr