name: Fortify Scan

on:
  push:
    branches:
      - main

env:
  FOD_URL: https://ams.fortify.com
  FOD_USERNAME: preferencial
  FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}
  FOD_RELEASE: zk4stv/election:main

jobs:
  fortify-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Fortify CLI
        run: |
          curl -sSL https://tools.fortify.com/fcli/install | bash
          fcli --version

      - name: Login to FoD
        run: |
          fcli fod login --tenant preferencial --username $FOD_USERNAME --password $FOD_PASSWORD --url $FOD_URL

      - name: Run Fortify scan
        run: |
          fcli translate start -bt python-pip -o preferencial.fpr .

      - name: Upload results to FoD (opcional)
        run: |
          fcli fod upload -r $FOD_RELEASE -a preferencial.fpr
