FOD_URL: https://ams.fortify.com
FOD_TENANT: dev-gubqx51ndecuf3as
FOD_USER: preferencial
FOD_PASSWORD: @Alpha100alpha100
FOD_RELEASE: zk4stv/election:main

FOD_SECURITY_CODE_METHOD: preferencial.org@gmail.com # ou 'sms'
FOD_SECURITY_CODE: 123456  # Este seria o código gerado dinamicamente

FOD_SINGLE_SESSION: true
FOD_FORCE_LOGOUT: false

IGNORED_DIRECTORIES:
  - /obj/
  - /logs/
  - /temp/

LOGGING:
  ENABLED: true
  LOG_PATH: /var/logs/fortify/
  LOG_LEVEL: INFO

BUILD:
  PACKAGE_MANAGER: NuGet
  TARGET_ENVIRONMENT: Azure
  PUBLISH: true
