name: Fortify Scan

on:
  push:
    branches:
      - main

env:
  FOD_URL: https://ams.fortify.com  # URL da instância do FoD
  FOD_USERNAME: preferencial  # Nome de usuário do FoD
  FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}  # Senha do FoD (armazenada como segredo)
  FOD_RELEASE: zk4stv/election:main

jobs:
  fortify-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Fortify
        uses: fortify/github-action/setup@v1.2.2

      - name: Login to FoD
        uses: fortify/github-action/internal/fod-login@v1.2.2

      - name: Run Fortify scan
        run: |
          fcli translate -bt python-pip -o preferencial.fpr .

      - name: Upload results to FoD (opcional)
        uses: fortify/github-action/fod-upload@v1.2.2
        with:
          artifact: preferencial.fpr
