curl -sSL -D - https://tools.fortify.com/fcli/install

name: Fortify Scan

on:
  push:
    branches:
      - main

env:
  FOD_URL: https://ams.fortify.com  # URL da instância do FoD
  FOD_USERNAME: preferencial  # Nome de usuário do FoD
  FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}  # Senha do FoD (armazenada como segredo)
  FOD_RELEASE: zk4stv/election:main  # Release no Fortify on Demand

jobs:
  fortify-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Fortify CLI
        run: |
          curl -sSL https://tools.fortify.com/fcli/install | bash
          fcli --version

      - name: Login to FoD
        run: |
          fcli fod login --tenant preferencial --username $FOD_USERNAME --password $FOD_PASSWORD --url $FOD_URL

      - name: Run Fortify scan
        run: |
          fcli translate start -bt python-pip -o preferencial.fpr .

      - name: Upload results to FoD (opcional)
        run: |
          fcli fod upload -r $FOD_RELEASE -a preferencial.fpr
