name: Fortify AST Scan

# Definir os eventos que disparam o workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '16 6 * * 1'  # Execução agendada semanalmente
  workflow_dispatch:

jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Fazer o checkout do código-fonte
      - name: Check Out Source Code
        uses: actions/checkout@v4

      # Instalar o Java necessário para executar ferramentas Fortify
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      # Instalar e configurar a Fortify CLI, caso ainda não esteja instalada
      - name: Install Fortify CLI
        run: |
          if ! command -v fcli &> /dev/null; then
            echo "Fortify CLI não encontrada, instalando."
            curl -f -sSL https://valid-url-for-fortify-cli/fortify-cli.sh -o install_fortify.sh || { echo "Erro ao baixar Fortify CLI"; exit 1; }
            chmod +x install_fortify.sh
            ./install_fortify.sh
          else
            echo "Fortify CLI já está instalada."
          fi

      # Verificar se a instalação da Fortify CLI foi bem-sucedida
      - name: Verify Fortify CLI Installation
        run: fcli --version

      # Executar a análise SAST via Fortify on Demand
      - name: Run FoD SAST Scan
        uses: fortify/github-action@a92347297e02391b857e7015792cd1926a4cd418
        with:
          sast-scan: true
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PASSWORD: ${{ secrets.FOD_PASSWORD }}

      # Opcionalmente, exportar os resultados da análise para o dashboard de alertas de segurança do GitHub
      - name: Export SAST Results to GitHub Code Scanning
        run: |
          # Exporte os resultados para o GitHub se necessário
          fcli upload -release ${{ secrets.FOD_RELEASE }} -f results.fpr
